### ISSUE TITLE
Neos Ui RSS

### ISSUE THREAD

**Issue by mhsdesign** [Sebobo/neos-dev-feeds#2]
## Neos Ui Rss Feeds

* [PRs](https://rsshub.app/github/pull/neos/neos-ui)
* [Issues](https://rsshub.app/github/issue/neos/neos-ui/all)
* [Commits](https://github.com/neos/neos-ui/commits.atom)

Maybe there is even a watcher for all other repos, so we dont miss things from https://github.com/neos/neos-base-distribution f.x.

**Comment by Sebobo** [comment]
Thx. Can you make a PR to add those few additional links?

I wasn't able to generate an Organization wide feed with filters. We could check the rsshub.app docs, if they provide something new.
